typography_spectrum: 0.30666887271218
color:
  brandStrength: 0.14501452073454857
  lightness: 0.5113983370829374
  saturation: 0.5515264950226992
  rhythmicContrast: 0.9322041010018438
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.506777707953006
name: Stronger Mommy
title: 'Essential Life Lessons Learned Through Some Trials & A Lot Of Errors '
description: From One Mom To Another. Helping You Learn From The Mistakes I Already Made...
